services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: jp_user
      POSTGRES_PASSWORD: jp_password
      POSTGRES_DB: jp_learning
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jp_user" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://jp_user:jp_password@db:5432/jp_learning
      # 选择使用 OpenAI 或 Azure OpenAI (二选一)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      # 或者使用 Azure OpenAI
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT:-}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY:-}
      AZURE_OPENAI_DEPLOYMENT: ${AZURE_OPENAI_DEPLOYMENT:-}
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: 8000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:


